import './simulation/planning-construction.test.mjs'
import './simulation/schedule-combat-needs.test.mjs'
import './simulation/services-production-population.test.mjs'
import './simulation/workplaces-households.test.mjs'
import './simulation/trade-agriculture-resources.test.mjs'
